#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 23 17:03:14 2018

@author: root
"""
import time
import picamera
camera = picamera.PiCamera()

while (True):
    camera.capture('temporal/image.jpg')
    
    camera.start_preview()

    for i in range(100):
        camera.brightness = i
        time.sleep(0.2)